const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// Deletes the duplicate "Swift-Bridging 2.h" that CocoaPods generates for RNScreens
// on newer Xcode versions. The file references RNScreens-Swift.h (a build-time artifact)
// via a non-module import path that doesn't resolve, breaking the build.
module.exports = function withRNScreensFix(config) {
  return withDangerousMod(config, [
    'ios',
    (mod) => {
      const podfilePath = path.join(mod.modRequest.platformProjectRoot, 'Podfile');
      let podfile = fs.readFileSync(podfilePath, 'utf8');

      const fix = `
  # Remove duplicate RNScreens Swift bridging header generated by CocoaPods on newer Xcode
  stale = File.join(installer.sandbox.root, 'Headers', 'Public', 'RNScreens', 'Swift-Bridging 2.h')
  File.delete(stale) if File.exist?(stale)`;

      // Inject into the first post_install block only
      podfile = podfile.replace(
        /post_install do \|installer\|/,
        `post_install do |installer|\n${fix}`,
      );

      fs.writeFileSync(podfilePath, podfile);
      return mod;
    },
  ]);
};
